<?php
/**
 * TABLE of CONTENTS
 *
 */

function adaptive_custom_panels_form_alter(&$form, &$form_state, $form_id){

  // dsm($form);
  if (($form_id == 'product_node_form') || ($form_id == 'page_node_form') || ($form_id == 'about_node_form') || ($form_id == 'customer_node_form') || ($form_id == 'event_node_form') || ($form_id == 'learn_node_form') || ($form_id == 'solutions_node_form')) {
      drupal_add_css(drupal_get_path('module', 'adaptive_custom_panels') . '/css/style1.css');
      drupal_add_js(drupal_get_path('module', 'adaptive_custom_panels') . '/js/script.js');
      $form['field_panel_type_']['und']['entities']['#table_fields']['type']['label'] = 'Panel Type';
      $form['field_panel_type_']['und']['actions']['ief_add']['#value'] = 'Add new panel';
      $form['field_panel_type_']['und']['form']['actions']['ief_add_save']['#value'] = 'Build Panel';
      $types = node_type_get_types();
      $type = $form['field_panel_type_']['und']['form']['#bundle'];
      $human_name = $types[$type]->name;
      $form['field_panel_type_']['und']['form']['#title'] = $human_name;
    }
  }

  /**
  * Implements hook_page_alter().
  */
  function adaptive_custom_panels_page_alter(&$page){
    if (arg(0) == 'node') {
      $nid = arg(1);
      $types = array(
        'product',
        'customer',
        'event',
        'learn',
        'blog',
        'solutions',
        'about',
        'page',
        'demo'
      );

      if (in_array(@$page['content']['system_main']['nodes'][$nid]['#node']->type, $types)) {
        $nnode = node_load($nid);

        // $lang=field_language('node',$nnode, 'field_panel_type_');
        if (isset($nnode->field_panel_type_[field_language('node', $nnode, 'field_panel_type_') ])) {
          foreach($nnode->field_panel_type_[field_language('node', $nnode, 'field_panel_type_') ] AS $rows) {

            // /for each start
            $entityID = $rows['target_id'];
            $add_block_unique = 'add_block_' . $entityID;
            $tnids = translation_node_get_translations($entityID);

            // if there is a translated version of this item, switch to that ID
            if (isset($tnids[$nnode->language])) {
              $entityID = $tnids[$nnode->language]->nid;
            }

            $node1 = node_load($entityID);

            // If this node doesn't exist anymore, the refrence is bad so skip this one and move on to the next.
            if (!$node1) {
              continue;
            }

            $hide = $node1->field_hide_titles[field_language('node', $node1, 'field_hide_titles') ][0]['value'];
            $region = $node1->field_region[field_language('node', $node1, 'field_region') ][0]['value'];
            $titletmp = $node1->title;
            $titlemain = '';

            if (isset($node1->body[field_language('node', $node1, 'body') ][0]['safe_value'])) {
              $copy1 = $node1->body[field_language('node', $node1, 'body') ][0]['safe_value'];
            }

            elseif (isset($node1->body[field_language('node', $node1, 'body') ][0]['value'])) {
              $copy1 = $node1->body[field_language('node', $node1, 'body') ][0]['value'];
            }

            else {
              $copy1 = '';
            }

            // establish page background and either container-fluid or container
            $pbg = $node1->field_background['und'][0]['value'];
            $panelcontainer = "container";

            if ($pbg == "1") { $panelcontainer = "panelbg container-fluid";}
            if ($node1->type == 'cta_panel') { $panelcontainer = "container-fluid";}

            // ONLY CUSTOM PANELS HAVE WIDTH TOGGLE, OTHERWISE WIDTH IS DETERMINED BY BGC or NOT
            if ($node1->type == 'custom_panel') {
              $pc = $node1->field_panel_contained['und'][0]['value'];
              if ($pc == "0") { $panelcontainer = "container";}
              if ($pc == "1") { $panelcontainer = "container-fluid";}
            }

            // DEFINES TITLEMAIN (PANEL TITLE) VARIABLE MARK UP FOR USE FOR ALL PANEL TYPES
            if (is_null($hide)) { $titlemain = '<h2>' . $titletmp . '</h2>';}

            // Defining all shared panel variables
            if ($node1->type == 'panel') {
              $img1 = '';
              $img2 = '';
              $img3 = '';
              $hr1 = '';
              $hr2 = '';
              $hr3 = '';
              $tid = $node1->field_panel_type[field_language('node', $node1, 'field_panel_type') ][0]['tid'];
              $term = taxonomy_term_load($tid);

              // TID31 full width single column paragraph panel
              // TID36 two column paragraph panel
              // TID41 three column paragraph panel

              if (($tid == 41) || ($tid == 36) || ($tid == 31)) {
                $name = 'panel-' . str_replace('Column', 'col', str_replace(' ', '-', $term->name));
              }

              // TID46 - FULL WIDTH IMAGE with two columns beneath
              // TID51
              // TID56
              elseif (($tid == 46) || ($tid == 51) || ($tid == 56)) {
                $name = 'panel-' . str_replace('Row', 'row', str_replace(' ', '-', $term->name));
              }

              // TID71 - 2 col hero
              elseif ($tid == 71) {
                $name = 'panel-2hero-col';
              }

              // TID76 - 3 col hero
              elseif ($tid == 76) {
                $name = 'panel-3hero-col';
              }

              $style = 'image-style-original';

              if (!is_null($node1->field_panel_images1[field_language('node', $node1, 'field_panel_images1') ][0]['uri'])) {
                $img1 = image_style_url($style, $node1->field_panel_images1[field_language('node', $node1, 'field_panel_images1') ][0]['uri']);
                $img1alt = $node1->field_panel_images1['und'][0]['alt'];
              }

              if (!is_null($node1->field_panel_images2[field_language('node', $node1, 'field_panel_images2') ][0]['uri'])) {
                $img2 = image_style_url($style, $node1->field_panel_images2[field_language('node', $node1, 'field_panel_images2') ][0]['uri']);
                $img2alt = $node1->field_panel_images1['und'][0]['alt'];
              }

              if (!is_null($node1->field_panel_images3[field_language('node', $node1, 'field_panel_images3') ][0]['uri'])) {
                $img3 = image_style_url($style, $node1->field_panel_images3[field_language('node', $node1, 'field_panel_images3') ][0]['uri']);
                $img3alt = $node1->field_panel_images1['und'][0]['alt'];
              }

              $alignyes = "";
              $alignyes2 = "";
              $alignyes3 = "";
              $align = $node1->field_align_right[field_language('node', $node1, 'field_align_right') ][0]['value'];
              $align2 = $node1->field_image_alignment_2[field_language('node', $node1, 'field_image_alignment_2') ][0]['value'];
              $align3 = $node1->field_image_alignment_3[field_language('node', $node1, 'field_image_alignment_3') ][0]['value'];

              if (isset($align)) {
                $alignyes = 'style="float:right"';
              }

              if (isset($align2)) {
                $alignyes2 = 'style="float:right"';
              }

              if (isset($align3)) {
                $alignyes3 = 'style="float:right"';
              }

              $rendered = '';
              if ($tid == 41) {
                $subtitile1 = $node1->field_panel_sub_title1[field_language('node', $node1, 'field_panel_sub_title1') ][0]['value'];
                $subtitile2 = $node1->field_panel_sub_title2[field_language('node', $node1, 'field_panel_sub_title2') ][0]['value'];
                $subtitile3 = $node1->field_panel_sub_title3[field_language('node', $node1, 'field_panel_sub_title3') ][0]['value'];
                $copy1 = $node1->field_panel_copy1[field_language('node', $node1, 'field_panel_copy1') ][0]['value'];
                $copy2 = $node1->field_panel_copy2[field_language('node', $node1, 'field_panel_copy2') ][0]['value'];
                $copy3 = $node1->field_panel_copy3[field_language('node', $node1, 'field_panel_copy3') ][0]['value'];
                $hr1 = $node1->field_add_hr1[field_language('node', $node1, 'field_add_hr1') ][0]['value'];
                $hr2 = $node1->field_add_hr2[field_language('node', $node1, 'field_add_hr2') ][0]['value'];
                $hr3 = $node1->field_add_hr3[field_language('node', $node1, 'field_add_hr3') ][0]['value'];
                $nodeclass = $node1->field_nodeclass['und'][0]['value'];
                $rendered.= '<div class="paragraph panelBox '. $nodeclass . ' tid41"><div class="row">';

                // Paragraph Panel Title renders here - toggle on/off in the UI
                if ($titlemain) { $rendered.= '<div class="col-lg-12">' . $titlemain . '</div>'; }

                $rendered.= '<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 panel-item">';

                if ($img1) { $rendered.= '<div class="panel-image"><img alt="' . $img1alt .' src="' . $img1 . '"></div>'; }

                $rendered.= '<div class="panel-copy">';
                $rendered.= '<h3>' . $subtitile1 . '</h3>';
                $rendered.= $copy1;
                $rendered.= '</div>';
                $rendered.= '</div>';
                $rendered.= '<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 panel-item">';

                if ($img2) {
                  $rendered.= '<div class="panel-image"><img alt="' . $img2alt .' src="' . $img2 . '"></div>';
                }

                $rendered.= '<div class="panel-copy">';
                $rendered.= '<h3>' . $subtitile2 . '</h3>';
                $rendered.= $copy2;
                $rendered.= '</div>';
                $rendered.= '</div>';
                $rendered.= '<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 panel-item">';

                if ($img3) {
                  $rendered.= '<div class="panel-image"><img alt="' . $img3alt .' src="' . $img3 . '"></div>';
                }

                $rendered.= '<div class="panel-copy">';
                $rendered.= '<h3>' . $subtitile3 . '</h3>';
                $rendered.= $copy3;
                $rendered.= '</div>';
                $rendered.= '</div>';
                $rendered.= '<div class="clearfix"></div>';
                $rendered.= '</div>';
                $rendered.= '</div>';

                if ($hr1) {
                  $rendered.= '<hr/>';
                }
              }

              elseif ($tid == 56) {
                $subtitile1 = $node1->field_panel_sub_title1[field_language('node', $node1, 'field_panel_sub_title1') ][0]['value'];
                $subtitile2 = $node1->field_panel_sub_title2[field_language('node', $node1, 'field_panel_sub_title2') ][0]['value'];
                $subtitile3 = $node1->field_panel_sub_title3[field_language('node', $node1, 'field_panel_sub_title3') ][0]['value'];
                $copy1 = $node1->field_panel_copy1[field_language('node', $node1, 'field_panel_copy1') ][0]['value'];
                $copy2 = $node1->field_panel_copy2[field_language('node', $node1, 'field_panel_copy2') ][0]['value'];
                $copy3 = $node1->field_panel_copy3[field_language('node', $node1, 'field_panel_copy3') ][0]['value'];
                $hr1 = $node1->field_add_hr1[field_language('node', $node1, 'field_add_hr1') ][0]['value'];
                $rendered = '';

                // PARAGRAPH PANEL - '1 Row'
                $nodeclass = $node1->field_nodeclass['und'][0]['value'];
                $rendered.= '<div class="panel-w-row paragraph panelBox '. $nodeclass . ' tid56"><div class="row">';

                // TITLEMAIN IS THE TITLE OF THE PANEL IN THE UI, NOT DISPLAY
                $rendered.= $titlemain;
                $rendered.= '<div class="panel-item">';

                if ($img1) {
                  $rendered.= '<div class="col-lg-6 col-sm-12 col-xs-12 panel-image"' . $alignyes . '><img alt="'.$img1alt.'" src="' . $img1 . '"></div>';
                }

                // PARAGRAPH PANEL - '2nd row'
                $rendered.= '<div class="col-lg-6 col-sm-12 col-xs-12 panel-copy">
                  <h3>' . $subtitile1 . '</h3>
                  ' . $copy1 . '</div>
                  <div class="clearfix"></div></div>
                  <hr />
                  <div class="panel-item">';

                if ($img2) {
                  $rendered.= '<div class="col-lg-6 col-sm-12 col-xs-12 panel-image"' . $alignyes2 . '>
                      <img alt="'. $img2alt.'" src="' . $img2 . '">
                    </div>';
                }

                // Paragraph Panel
                $rendered.= '<div class="col-lg-6 col-sm-12 col-xs-12 panel-copy"><h3>' . $subtitile2 . '</h3>' . $copy2 . '</div><div class="clearfix"></div></div><hr /><div class="panel-item">';

                if ($img3) {
                  $rendered.= '<div class="col-lg-6 col-sm-12 col-xs-12 panel-image"' . $alignyes3 . '><img alt="'. $img3alt.'" src="' . $img3 . '"></div>';
                }

                // Paragraph Panel Third Item
                $rendered.= '<div class="col-lg-6 col-sm-12 col-xs-12 panel-copy">';
                $rendered.= '<h3>' . $subtitile3 . '</h3>';
                $rendered.= $copy3;
                $rendered.= '</div>';
                $rendered.= '<div class="clearfix"></div>';
                $rendered.= '</div>';

                if ($hr1) {
                  $rendered.= '<hr />';
                }
                $rendered.= '</div>';
                $rendered.= '</div>';
              }

              // Two column paragraph panel with titles
              elseif ($tid == 36) {
                $subtitile1 = $node1->field_panel_sub_title1[field_language('node', $node1, 'field_panel_sub_title1') ][0]['value'];
                $subtitile2 = $node1->field_panel_sub_title2[field_language('node', $node1, 'field_panel_sub_title2') ][0]['value'];
                $copy1 = $node1->field_panel_copy1[field_language('node', $node1, 'field_panel_copy1') ][0]['value'];
                $copy2 = $node1->field_panel_copy2[field_language('node', $node1, 'field_panel_copy2') ][0]['value'];
                $hr1 = $node1->field_add_hr1[field_language('node', $node1, 'field_add_hr1') ][0]['value'];
                $rendered = '';
                $nodeclass = $node1->field_nodeclass['und'][0]['value'];
                $rendered.= '<div class="paragraph panelBox'. $nodeclass . ' tid36 p2c"><div class="row">';
                $rendered.= '<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">' . $titlemain . '</div>';
                $rendered.= '<div class="col-lg-6 col-sm-12 col-xs-12 panel-item">';

                if ($img1) {
                  $rendered.= '<div class="panel-image"><img alt="' .$img1alt.'" src="' . $img1 . '"></div>';
                }

                $rendered.= '<div class="panel-copy">';
                $rendered.= '<h3>' . $subtitile1 . '</h3>';
                $rendered.= $copy1;
                $rendered.= '</div>';
                $rendered.= '</div>';
                $rendered.= '<div class="col-lg-6 col-sm-12 col-xs-12 panel-item">';

                if ($img2) {
                  $rendered.= '<div class="panel-image"><img alt="'.$img2alt.'" src="' . $img2 . '"></div>';
                }

                $rendered.= '<div class="panel-copy">';
                $rendered.= '<h3>' . $subtitile2 . '</h3>';
                $rendered.= $copy2;
                $rendered.= '</div>';
                $rendered.= '</div>';
                $rendered.= '</div>';
                $rendered.= '<div class="clearfix"></div>';
                $rendered.= '</div>';

                if ($hr1) {
                  $rendered.= '<hr/>';
                }
              }

              elseif ($tid == 51) {
                $subtitile1 = $node1->field_panel_sub_title1[field_language('node', $node1, 'field_panel_sub_title1') ][0]['value'];
                $subtitile2 = $node1->field_panel_sub_title2[field_language('node', $node1, 'field_panel_sub_title2') ][0]['value'];
                $copy1 = $node1->field_panel_copy1[field_language('node', $node1, 'field_panel_copy1') ][0]['value'];
                $copy2 = $node1->field_panel_copy2[field_language('node', $node1, 'field_panel_copy2') ][0]['value'];
                $hr1 = $node1->field_add_hr1[field_language('node', $node1, 'field_add_hr1') ][0]['value'];
                $rendered = '';

                // panel rows 2
                $nodeclass = $node1->field_nodeclass['und'][0]['value'];
                $rendered.= '<div class="panel-w-row paragraph panelBox '. $nodeclass . ' tid51"><div class="row">';
                $rendered.= '<div class="col-lg-12">' . $titlemain . '</div>';
                $rendered.= '<div class="panel-item">';

                if ($img1) {
                  $rendered.= '<div class="col-lg-6 col-sm-12 col-xs-12 panel-image"' . $alignyes . '><img src="' . $img1 . '"></div>';
                }

                $rendered.= '<div class="col-lg-6 col-sm-12 col-xs-12 panel-copy">';
                $rendered.= '<h3>' . $subtitile1 . '</h3>';
                $rendered.= $copy1;
                $rendered.= '</div>';
                $rendered.= '<div class="clearfix"></div>';
                $rendered.= '</div>';
                $rendered.= '<hr />';
                $rendered.= '<div class="panel-item">';

                if ($img2) {
                  $rendered.= '<div class="col-lg-6 col-sm-12 col-xs-12 panel-image"' . $alignyes2 . '><img src="' . $img2 . '"></div>';
                }

                $rendered.= '<div class="col-lg-6 col-sm-12 col-xs-12 panel-copy">';
                $rendered.= '<h3>' . $subtitile2 . '</h3>';
                $rendered.= $copy2;
                $rendered.= '</div>';
                $rendered.= '<div class="clearfix"></div>';
                $rendered.= '</div>';

                if ($hr1) {
                  $rendered.= '<hr>';
                }

                $rendered.= '</div>';
                $rendered.= '</div>';
              }

              // PARAGRAPH PANEL NO IMAGE FULL WIDTH
              elseif ($tid == 31) {
                $subtitile1 = $node1->field_panel_sub_title1[field_language('node', $node1, 'field_panel_sub_title1') ][0]['value'];
                $copy1 = $node1->field_panel_copy1[field_language('node', $node1, 'field_panel_copy1') ][0]['value'];
                $hr1 = $node1->field_add_hr1[field_language('node', $node1, 'field_add_hr1') ][0]['value'];
                $rendered = '';
                $nodeclass = $node1->field_nodeclass['und'][0]['value'];
                $rendered.= '
                  <div class="panel-item paragraph panelBox '. $nodeclass . ' tid31">
                  <div class="row">
                  <div class="col-sm-12">' . $titlemain . '<h3>' . $subtitile1 . '</h3><div class="panel-copy">' . $copy1 . '</div></div></div><div class="clearfix"></div></div>';
                if ($hr1) {
                  $rendered.= '<hr>';
                }
              }

              // PARAGRAPH PANEL - 1 Row
              elseif ($tid == 46) {
                $subtitile1 = $node1->field_panel_sub_title1[field_language('node', $node1, 'field_panel_sub_title1') ][0]['value'];
                $copy1 = $node1->field_panel_copy1[field_language('node', $node1, 'field_panel_copy1') ][0]['value'];
                $hr1 = $node1->field_add_hr1[field_language('node', $node1, 'field_add_hr1') ][0]['value'];
                $rendered = '';
                $nodeclass = $node1->field_nodeclass['und'][0]['value'];
                $rendered.= '<div class="panel-w-row paragraph panelBox'. $nodeclass . ' tid46"><div class="row">';
                $rendered.= '<div class="col-lg-12">' . $titlemain . '</div>';
                $rendered.= '<div class="panel-item">';

                if ($img1) {
                  $rendered.= '<div class="col-lg-6 col-sm-12 col-xs-12 panel-image"' . $alignyes . '><img src="' . $img1 . '"></div>';
                }

                $rendered.= '<div class="col-lg-6 col-sm-12 col-xs-12 panel-copy">';
                $rendered.= '<h3>' . $subtitile1 . '</h3>';
                $rendered.= $copy1;
                $rendered.= '</div>';
                $rendered.= '<div class="clearfix"></div>';
                $rendered.= '</div>';

                if ($hr1) {
                  $rendered.= '<hr>';
                }

                $rendered.= '</div>';
                $rendered.= '</div>';
                $rendered.= '</div>';
              }

              // PARAGRAPH PANEL - 2 COL HERO
              elseif ($tid == 71) {
                $subtitile1 = $node1->field_panel_sub_title1[field_language('node', $node1, 'field_panel_sub_title1') ][0]['value'];
                $subtitile2 = $node1->field_panel_sub_title2[field_language('node', $node1, 'field_panel_sub_title2') ][0]['value'];
                $copy1 = $node1->field_panel_copy1[field_language('node', $node1, 'field_panel_copy1') ][0]['value'];
                $copy2 = $node1->field_panel_copy2[field_language('node', $node1, 'field_panel_copy2') ][0]['value'];
                $rendered = '';
                $nodeclass = $node1->field_nodeclass['und'][0]['value'];
                $rendered.= '<div class="paragraph panelBox '. $nodeclass . 'tid71"><div class="row">';
                $rendered.= $titlemain;

                if ($img1) {
                  $rendered.= '<div class="panel-item col-xs-12"><div class="panel-image"><img src="' . $img1 . '"/></div></div>';
                }

                $rendered.= '<div class="panel-item col-xs-12 col-sm-6   col-lg-6"><div class="panel-copy"><h3>' . $subtitile1 . '</h3>';
                $rendered.= $copy1;
                $rendered.= '</div></div><div class="panel-item col-xs-12 col-sm-6 col-lg-6"><div class="panel-copy"><h3>' . $subtitile2 . '</h3>';
                $rendered.= $copy2;
                $rendered.= '</div></div></div></div><div class="clearfix"></div>';
              }

              elseif ($tid == 76) {
                $subtitile1 = $node1->field_panel_sub_title1[field_language('node', $node1, 'field_panel_sub_title1') ][0]['value'];
                $subtitile2 = $node1->field_panel_sub_title2[field_language('node', $node1, 'field_panel_sub_title2') ][0]['value'];
                $subtitile3 = $node1->field_panel_sub_title3[field_language('node', $node1, 'field_panel_sub_title3') ][0]['value'];
                $copy1 = $node1->field_panel_copy1[field_language('node', $node1, 'field_panel_copy1') ][0]['value'];
                $copy2 = $node1->field_panel_copy2[field_language('node', $node1, 'field_panel_copy2') ][0]['value'];
                $copy3 = $node1->field_panel_copy3[field_language('node', $node1, 'field_panel_copy3') ][0]['value'];
                $rendered = '';

                // PARAGRAPH PANEL - 3 column Hero
                $nodeclass = $node1->field_nodeclass['und'][0]['value'];
                $rendered.= '<div class="paragraph panelBox'. $nodeclass . ' tid76"><div class="row">';
                $rendered.= $titlemain;

                if ($img1) {
                  $rendered.= '<div class="panel-item col-xs-12"><div class="panel-image"><img src="' . $img1 . '"/></div></div>';
                }

                $rendered.= '<div class="panel-item col-xs-12 col-sm-12 col-md-4 col-lg-4"><div class="panel-copy">';
                $rendered.= '<h3>' . $subtitile1 . '</h3>';
                $rendered.= $copy1;
                $rendered.= '</div></div><div class="panel-item col-xs-12 col-sm-12 col-md-4  col-lg-4">';
                $rendered.= '<div class="panel-copy">';
                $rendered.= '<h3>' . $subtitile2 . '</h3>';
                $rendered.= $copy2;
                $rendered.= '</div></div><div class="panel-item col-xs-12 col-sm-12 col-md-4  col-lg-4"><div class="panel-copy">';
                $rendered.= '<h3>' . $subtitile3 . '</h3>' . $copy3 . '</div></div></div><div class="clearfix"></div>';
                $rendered.= '</div>';
              }
            }

            // Content type Custom Panel
            elseif ($node1->type == 'custom_panel') {
              $nodeclass = $node1->field_nodeclass['und'][0]['value'];
              $rendered = '<div class="panelBox '. $nodeclass . '">';
              $rendered.= '<div class="panel-item">';

              // Custom Panel Title renders here - toggle on/off in the UI
              $rendered.= $titlemain;
              $rendered.= '<div class="panel-copy">' . $copy1 . '</div></div><div class="clearfix"></div></div>';
            }

            // Content type CTA Panel
            elseif ($node1->type == 'cta_panel') {
              if ($node1->field_panel_contained['und'][0]['value']='1') {
                $nodeclass = $node1->field_nodeclass['und'][0]['value'];
                $rendered = '<div class="inner-cta-wrapper">';
                $rendered.= $titlemain;
                $rendered.= $copy1;
                $rendered.= '</div>';
              }

              else {
                $nodeclass = $node1->field_nodeclass['und'][0]['value'];
                $rendered = '<div>';
                $rendered.= $titlemain;
                $rendered.= $copy1;
                $rendered.= '</div>';
              }
            }

            // Content type Hero // Content type Hero Panel
            elseif ($node1->type == 'hero_panel') {
              $uuid = $node1->field_video_player_uuid[field_language('node', $node1, 'field_video_player_uuid') ][0]['value'];
              $nodeclass = $node1->field_nodeclass['und'][0]['value'];
              $rendered = '<div class="panelBox '. $nodeclass . '">';
              $rendered.= '<div class="panel-item">';
              $rendered.= $titlemain;
              $rendered.= '<div class="panel-copy">';
              $rendered.= $copy1;

              if (!is_null($uuid)) {
                $rendered.= '
                  <div class="videoContainer">
                    <a href="http://play.vidyard.com/' . $uuid . '.html">
                    <span class="play_button">
                    <img class="lang lang-alt lang-title"title="Play Video"src="/sites/all/themes/splash/assets/images/black_play_button_up.png"alt="Play Video">
                    </span>
                    <img class="splash"src="http://play.vidyard.com/' . $uuid . '.jpg">
                    </a>
                  </div>';
              }

              $rendered.= '</div>';
              $rendered.= '</div>';
              $rendered.= '<div class="clearfix"></div>';
              $rendered.= '</div>';
            }

            // Content type quotes Panel
            elseif ($node1->type == 'quote_panel') {
              $img1 = '';
              $img2 = '';
              $tid = $node1->field_layout_type_quotes[field_language('node', $node1, 'field_layout_type_quotes') ][0]['value'];
              $node_cust_entityid = $node1->field_customer_success_link[field_language('node', $node1, 'field_customer_success_link') ][0]['target_id'];
              $node_cust_tnids = translation_node_get_translations($node_cust_entityid);

              // if there is a translated version of this item, switch to that ID
              if (isset($node_cust_tnids[$nnode->language])) {
                $node_cust_entityid = $node_cust_tnids[$nnode->language]->nid;
              }

              $node_cust = node_load($node_cust_entityid);
              $subtitile1 = $node1->field_panel_sub_title1[field_language('node', $node1, 'field_panel_sub_title1') ][0]['value'];
              $img1 = file_create_url($node1->field_panel_images1[field_language('node', $node1, 'field_panel_images1') ][0]['uri']);
              $img1alt = $node1->field_panel_images1['und'][0]['alt'];
              $img2 = file_create_url($node1->field_panel_images2[field_language('node', $node1, 'field_panel_images2') ][0]['uri']);
              $img2alt = $node1->field_panel_images2['und'][0]['alt'];
              $clink = '//' . $node1->field_button_link[field_language('node', $node1, 'field_buttton_link') ][0]['url'];
              $rendered = '';
              $nodeclass = $node1->field_nodeclass['und'][0]['value'];
              $rendered.= '<div class="panel-1-col panel-quote '. $nodeclass . '">';

              if ($tid == 3) {
                $rendered.= '<div class="panel-copy panel-quote-no-logo panelBox row">';
                $rendered.= $titlemain;
                $rendered.= $copy1;
                $rendered.= '</div>';
                $rendered.= '<div class="clearfix"></div>';
              }

              elseif ($tid == 2) {
                $rendered.= '<div class="panel-quote-logo panelBox">';
                $rendered.= $titlemain;

                if ($img2) {
                  $rendered.= '<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 panel-image pqlReal"><img alt="'. $img2alt .'" src="' . $img2 . '"/></div>';
                }

                $rendered.= '<div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 panel-copy">';
                // $rendered.= '<h3>' . $subtitile1 . '</h3>';

                $rendered.= $copy1;
                $rendered.= '</div>';
                $rendered.= '<div class="clearfix"></div>';
                $rendered.= '</div>';
              }

              elseif ($tid == 1) {
                $rendered.= '<div class="panel-quote-photo panelBox">';
                $rendered.= $titlemain;

                if ($img1) {
                  $rendered.= '<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 panel-image"><img alt="' .$img1alt.'" src="' . $img1 . '"/></div>';
                }

                $rendered.= '<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 panel-copy">';

                if ($img2) {
                  $rendered.= '<div class="panel-image-logo"><img alt="' . $img2alt.'" src="' . $img2 . '"></div>';
                }

                $rendered.= '<h3>' . $subtitile1 . '</h3>';
                $rendered.= $copy1;
                $rendered.= '</div>';
                $rendered.= '<div class="clearfix"></div>';
                $rendered.= '</div>';
              }

              $rendered.= '</div>';
            }

            elseif ($node1->type == 'social_panel') {
              $block_arr = explode(':', $node1->field_select_block[field_language('node', $node1, 'field_select_block') ][0]['moddelta']);
              $block = block_load($block_arr[0], $block_arr[1]);
              $block = _block_render_blocks(array( $block ));
              $block_build = _block_get_renderable_array($block);
              $block_arr = explode(':', $node1->field_sharethis_print_friendly[field_language('node', $node1, 'field_sharethis_print_friendly') ][0]['moddelta']);
              $block = block_load($block_arr[0], $block_arr[1]);
              $block = _block_render_blocks(array( $block ));
              $block_build2 = _block_get_renderable_array($block);
              $nodeclass = $node1->field_nodeclass['und'][0]['value'];
              $rendered = '<div class="panelBox '. $nodeclass . '"> ';
              $rendered.= $titlemain;
              $rendered.= drupal_render($block_build2);
              $rendered.= drupal_render($block_build);
              $rendered.= '</div>';
            }

            // begin carousel panl with node class
            elseif ($node1->type == 'carousel_panel') {
              $block_arr = explode(':', $node1->field_select_block[field_language('node', $node1, 'field_select_block') ][0]['moddelta']);
              $block = block_load($block_arr[0], $block_arr[1]);
              $block = _block_render_blocks(array( $block ));
              $block_build = _block_get_renderable_array($block);
              $nodeclass = $node1->field_nodeclass['und'][0]['value'];
              $rendered = '<div class="panelBox '. $nodeclass . '">';
              $rendered.= $titlemain;
              $rendered.= drupal_render($block_build);
              $rendered.= '</div>';
            }

            elseif ($node1->type == 'panel_hero_video') {
              drupal_add_js('http://play.vidyard.com/v0/api.js', 'external');
              $bspath = libraries_get_path('bxslider');
              drupal_add_js($bspath . '/jquery.bxslider.js');
              drupal_add_css($bspath . '/jquery.bxslider.css');
              $video_output = array();
              $vid_ids = array();

              foreach($node1->field_video_player[field_language('node', $node1, 'field_video_player') ] as $vkey => $vvalue) {
                $video_entity = field_collection_item_load($vvalue['value']);
                $vid_id = $video_entity->field_video_player_uuid[field_language('field_collection_item', $video_entity, 'field_video_player_uuid') ? : LANGUAGE_NONE][0]['value'];
                $vidimguri = $video_entity->field_image[field_language('field_collection_item', $video_entity, 'field_image') ? : LANGUAGE_NONE][0]['uri'];
                $vid_img = $vidimguri ? file_create_url($vidimguri) : '';
                $vid_text = $video_entity->field_video_text[field_language('field_collection_item', $video_entity, 'field_video_text') ? : LANGUAGE_NONE][0]['safe_value'];
                $video_descr = '';

                if (!is_null($vidimguri)) {
                  $video_descr.= '
                  <div class="panel-quote">
                    <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12 panel-image"><img src="' . $vid_img . '"/></div>
                    <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12 panel-copy">' . $vid_text . '</div>
                    <div class="clearfix"></div>
                  </div>';
                }

                else {
                  if (strlen($vid_text) > 10) {
                    $video_descr.= '
                    <div class="panel-quote">
                      <div class="panel-quote-padded">
                      ' . $vid_text . '
                      </div>
                    </div>';
                  }
                  else { $video_descr.= ''; }
                }

                if (isset($vid_id)) {
                  $video_output[$vkey] = '
                  <div class="panel-quote-video">
                    <div class="col-lg-12"style="padding: 0">
                        <div class="videoContainer">
                          <a href="http://play.vidyard.com/' . $vid_id . '.html">
                            <span class="play_button">
                              <img class="lang lang-alt lang-title"title="Play Video"src="/sites/all/themes/splash/assets/images/black_play_button_up.png"alt="Play Video">
                            </span>
                            <img class="splash"src="http://play.vidyard.com/' . $vid_id . '.jpg">
                          </a>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                  </div>';
                }

                else { $video_output[$vkey] = '';}

                $vid_ids[] = $vid_id;
                $video_output[$vkey].= $video_descr;
              }

              drupal_add_js('
                jQuery(document).ready(function() {
                  if($(".bxslide").length < 4) {
                    console.log();
                    $(".bx-controls").hide();
                  }
                });
                ', array(
                  'type' => 'inline',
                  'scope' => 'footer',
                  'weight' => 5
                )
              );

              $rendered = '';

              // <!-- starting Hero Video panel here -->
              $nodeclass = $node1->field_nodeclass['und'][0]['value'];
              $rendered.= '<div class="panelBox '. $nodeclass . '"><div class="dexp-bxslider" id="video-slider-block">';

              foreach($video_output as $video_key => $video_val) {
                if (!empty($video_val)) {
                  $rendered.= '<div class="bxslide">';
                  $rendered.= $video_val;
                  $rendered.= '</div>';
                }
              }

              $rendered.= '</div></div>';
            }

            // content type fact Panel
            elseif ($node1->type == 'fact_panel') {
              $rendered = '';
              $nodeclass = $node1->field_nodeclass['und'][0]['value'];
              $rendered.= '<div class="panelBox'. $nodeclass . '"><div class="panel-item">';
              $rendered.= $titlemain;
              $rendered.= $copy1;
              $rendered.= '</div></div>';
            }

            // Content type ( featured_case_study ) Featured Case study Panel
            elseif ($node1->type == 'featured_case_study') {
              $tid = $node1->field_layout_type_3_column[field_language('node', $node1, 'field_layout_type_3_column') ][0]['value'];
              $img1 = '';
              $img2 = '';
              $img3 = '';
              $miniimg1 = '';
              $miniimg2 = '';
              $miniimg3 = '';
              $linkurl1 = '';
              $linkurl2 = '';
              $linkurl3 = '';
              $hr1 = '';
              $hr2 = '';
              $hr3 = '';
              $style = 'image-style-original';
              $ministyle = 'image-style-original';

              if (!is_null($node1->field_panel_images1[field_language('node', $node1, 'field_panel_images1') ][0]['uri'])) {
                $img1 = image_style_url($style, $node1->field_panel_images1[field_language('node', $node1, 'field_panel_images1') ][0]['uri']);
                $img1alt = $node1->field_panel_images1['und'][0]['alt'];
              }

              if (!is_null($node1->field_panel_images2[field_language('node', $node1, 'field_panel_images2') ][0]['uri'])) {
                $img2 = image_style_url($style, $node1->field_panel_images2[field_language('node', $node1, 'field_panel_images2') ][0]['uri']);
                $img2alt = $node1->field_panel_images2['und'][0]['alt'];
              }

              if (!is_null($node1->field_panel_images3[field_language('node', $node1, 'field_panel_images3') ][0]['uri'])) {
                $img3 = image_style_url($style, $node1->field_panel_images3[field_language('node', $node1, 'field_panel_images3') ][0]['uri']);
                $img3alt = $node1->field_panel_images3['und'][0]['alt'];
              }

              if (!is_null($node1->field_panel_logo1[field_language('node', $node1, 'field_panel_logo1') ][0]['uri'])) {
                $miniimg1 = ' <div class="mini-logo"><img src="' . image_style_url($ministyle, $node1->field_panel_logo1[field_language('node', $node1, 'field_panel_logo1') ][0]['uri']) . '"></div>';
              }

              if (!is_null($node1->field_panel_logo2[field_language('node', $node1, 'field_panel_logo2') ][0]['uri'])) {
                $miniimg2 = ' <div class="mini-logo"><img src="' . image_style_url($ministyle, $node1->field_panel_logo2[field_language('node', $node1, 'field_panel_logo2') ][0]['uri']) . '"></div>';
              }

              if (!is_null($node1->field_panel_logo3[field_language('node', $node1, 'field_panel_logo3') ][0]['uri'])) {
                $miniimg3 = ' <div class="mini-logo"><img src="' . image_style_url($ministyle, $node1->field_panel_logo3[field_language('node', $node1, 'field_panel_logo3') ][0]['uri']) . '"></div>';
              }

              if (!is_null($node1->field_panel_button_link1[field_language('node', $node1, 'field_panel_button_link1') ][0]['url'])) {
                $linkurl1 = 'http://' . $node1->field_panel_button_link1[field_language('node', $node1, 'field_panel_button_link1') ][0]['url'];
              }

              if (!is_null($node1->field_panel_button_link2[field_language('node', $node1, 'field_panel_button_link2') ][0]['url'])) {
                $linkurl2 = 'http://' . $node1->field_panel_button_link2[field_language('node', $node1, 'field_panel_button_link2') ][0]['url'];
              }

              if (!is_null($node1->field_panel_button_link3[field_language('node', $node1, 'field_panel_button_link3') ][0]['url'])) {
                $linkurl3 = 'http://' . $node1->field_panel_button_link3[field_language('node', $node1, 'field_panel_button_link3') ][0]['url'];
              }

              $rendered = '';

              if ($tid == 3) {
                $subtitile1 = $node1->field_panel_sub_title1[field_language('node', $node1, 'field_panel_sub_title1') ][0]['value'];
                $subtitile2 = $node1->field_panel_sub_title2[field_language('node', $node1, 'field_panel_sub_title2') ][0]['value'];
                $subtitile3 = $node1->field_panel_sub_title3[field_language('node', $node1, 'field_panel_sub_title3') ][0]['value'];
                $copy1 = $node1->field_panel_copy1[field_language('node', $node1, 'field_panel_copy1') ][0]['value'];
                $copy2 = $node1->field_panel_copy2[field_language('node', $node1, 'field_panel_copy2') ][0]['value'];
                $copy3 = $node1->field_panel_copy3[field_language('node', $node1, 'field_panel_copy3') ][0]['value'];
                $hr1 = $node1->field_add_hr1[field_language('node', $node1, 'field_add_hr1') ][0]['value'];
                $hr2 = $node1->field_add_hr2[field_language('node', $node1, 'field_add_hr2') ][0]['value'];
                $hr3 = $node1->field_add_hr3[field_language('node', $node1, 'field_add_hr3') ][0]['value'];
                $nodeclass = $node1->field_nodeclass['und'][0]['value'];
                $rendered.= '<div class="panel-3-col panel-cs">';
                $rendered.= '<div class="panelBox '. $nodeclass . '">';
                $rendered.= $titlemain;
                $rendered.= '<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 panel-item">';

                if ($img1) {
                  $rendered.= '<div class="panel-image"><img ' .$img1alt. ' src="' . $img1 . '">' . $miniimg1 . '</div>';
                }

                $rendered.= '<div class="panel-copy">';
                $rendered.= '<h3>' . $subtitile1 . '</h3>';
                $rendered.= $copy1;

                if ($linkurl1) {
                  $rendered.= '<p><a href="' . $linkurl1 . '" class="btn btn-primary">Learn More</a></p>';
                }

                if ($hr1) {
                  $rendered.= '<hr/>';
                }

                $rendered.= '</div>';
                $rendered.= '</div>';
                $rendered.= '<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 panel-item">';

                if ($img2) {
                  $rendered.= '<div class="panel-image"><img ' .$img2alt.' src="' . $img2 . '">' . $miniimg2 . '</div>';
                }

                $rendered.= '<div class="panel-copy">';
                $rendered.= '<h3>' . $subtitile2 . '</h3>';
                $rendered.= $copy2;

                if ($linkurl2) {
                  $rendered.= '<p><a href="' . $linkurl2 . '" class="btn btn-primary">Learn More</a></p>';
                }

                if ($hr2) {
                  $rendered.= '<hr/>';
                }

                $rendered.= '</div>';
                $rendered.= '</div>';
                $rendered.= '<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 panel-item">';

                if ($img3) {
                  $rendered.= '  <div class="panel-image"><img ' .$img3alt. ' src="' . $img3 . '">' . $miniimg3 . '</div>';
                }

                $rendered.= '<div class="panel-copy">';
                $rendered.= '<h3>' . $subtitile3 . '</h3>';
                $rendered.= $copy3;

                if ($linkurl3) {
                  $rendered.= '<p><a href="' . $linkurl3 . '" class="btn btn-primary">Learn More</a></p>';
                }

                if ($hr3) {
                  $rendered.= '<hr/>';
                }

                $rendered.= '</div>';
                $rendered.= '</div>';
                $rendered.= '<div class="clearfix"></div>';
                $rendered.= '</div>';
                $rendered.= '</div>';
              }

              elseif ($tid == 2) {
                $subtitile1 = $node1->field_panel_sub_title1[field_language('node', $node1, 'field_panel_sub_title1') ][0]['value'];
                $subtitile2 = $node1->field_panel_sub_title2[field_language('node', $node1, 'field_panel_sub_title2') ][0]['value'];
                $copy1 = $node1->field_panel_copy1[field_language('node', $node1, 'field_panel_copy1') ][0]['value'];
                $copy2 = $node1->field_panel_copy2[field_language('node', $node1, 'field_panel_copy2') ][0]['value'];
                $hr1 = $node1->field_add_hr1[field_language('node', $node1, 'field_add_hr1') ][0]['value'];
                $hr2 = $node1->field_add_hr2[field_language('node', $node1, 'field_add_hr2') ][0]['value'];
                $rendered = '';
                $rendered.= '<div class="panel-2-col panel-cs">';
                $rendered.= '<div class="panelBox">';
                $rendered.= $titlemain;
                $rendered.= '<div class="col-lg-6 col-sm-6 col-xs-12 panel-item">';

                if ($img1) {
                  $rendered.= '<div class="panel-image"><img ' .$img1alt.' src="' . $img1 . '">' . $miniimg1 . '</div>';
                }

                $rendered.= '<div class="panel-copy">';
                $rendered.= '<h3>' . $subtitile1 . '</h3>';
                $rendered.= $copy1;

                if ($linkurl1) {
                  $rendered.= '<p><a href="' . $linkurl1 . '"class="btn btn-primary">Learn More</a></p>';
                }

                if ($hr1) {
                  $rendered.= '<hr/>';
                }

                $rendered.= '</div>';
                $rendered.= '</div>';
                $rendered.= '<div class="col-lg-6 col-sm-6 col-xs-12 panel-item">';

                if ($img2) {
                  $rendered.= '<div class="panel-image"><img ' .$img2alt.' src="' . $img2 . '">' . $miniimg2 . '</div>';
                }

                $rendered.= '<div class="panel-copy">';
                $rendered.= '<h3>' . $subtitile2 . '</h3>';
                $rendered.= $copy2;

                if ($linkurl2) {
                  $rendered.= '<p><a href="' . $linkurl2 . '"class="btn btn-primary">Learn More</a></p>';
                }

                if ($hr2) {
                  $rendered.= '<hr/>';
                }

                $rendered.= '</div>';
                $rendered.= '</div>';
                $rendered.= '<div class="clearfix"></div>';
                $rendered.= '</div>';
                $rendered.= '</div>';
              }

              elseif ($tid == 1) {
                $subtitile1 = $node1->field_panel_sub_title1[field_language('node', $node1, 'field_panel_sub_title1') ][0]['value'];
                $copy1 = $node1->field_panel_copy1[field_language('node', $node1, 'field_panel_copy1') ][0]['value'];
                $hr1 = $node1->field_add_hr1[field_language('node', $node1, 'field_add_hr1') ][0]['value'];
                $rendered.= '<div class="panel-1-col panel-cs">';
                $rendered.= '<div class="panelBox">';
                $rendered.= $titlemain;
                $rendered.= '<div class="col-xs-12 panel-item">';

                if ($img1) {
                  $rendered.= '  <div class="panel-image"><img ' .$img1alt.' src="' . $img1 . '">' . $miniimg1 . '</div>';
                }

                $rendered.= '<div class="panel-copy">';
                $rendered.= '<h3>' . $subtitile1 . '</h3>';
                $rendered.= $copy1;

                if ($linkurl1) {
                  $rendered.= '<p><a href="' . $linkurl1 . '"class="btn btn-primary">Learn More</a></p>';
                }

                if ($hr1) {
                  $rendered.= '<hr/>';
                }

                $rendered.= '</div>';
                $rendered.= '</div>';
                $rendered.= '<div class="clearfix"></div>';
                $rendered.= '</div>';
                $rendered.= '</div>';
              }
            }

            // Promo Panel
            elseif ($node1->type == 'promo_panel') {
              $tid = $node1->field_layout_type_2c1r[field_language('node', $node1, 'field_layout_type_2c1r') ][0]['value'];
              $img1 = '';
              $img2 = '';
              $img3 = '';
              $miniimg1 = '';
              $miniimg2 = '';
              $miniimg3 = '';
              $linkurl1 = '';
              $linkurl2 = '';
              $style = 'image-style-original';
              $ministyle = 'image-style-original';

              if (!is_null($node1->field_panel_images1[field_language('node', $node1, 'field_panel_images1') ][0]['uri'])) {
                $img1 = image_style_url($style, $node1->field_panel_images1[field_language('node', $node1, 'field_panel_images1') ][0]['uri']);
                $img1alt = $node1->field_panel_images1['und'][0]['alt'];
              }

              if (!is_null($node1->field_panel_images2[field_language('node', $node1, 'field_panel_images2') ][0]['uri'])) {
                $img2 = image_style_url($style, $node1->field_panel_images2[field_language('node', $node1, 'field_panel_images2') ][0]['uri']);
                $img2alt = $node1->field_panel_images2['und'][0]['alt'];
              }

              if (!is_null($node1->field_panel_button_link1[field_language('node', $node1, 'field_panel_button_link1') ][0]['url'])) {
                $linkurl1 = 'http://' . $node1->field_panel_button_link1[field_language('node', $node1, 'field_panel_button_link1') ][0]['url'];
              }

              if (!is_null($node1->field_panel_button_link2[field_language('node', $node1, 'field_panel_button_link2') ][0]['url'])) {
                $linkurl2 = 'http://' . $node1->field_panel_button_link2[field_language('node', $node1, 'field_panel_button_link2') ][0]['url'];
              }

              $rendered = '';

              if ($tid == 3) {
                $subtitile1 = $node1->field_panel_sub_title1[field_language('node', $node1, 'field_panel_sub_title1') ][0]['value'];
                $copy1 = $node1->field_panel_copy1[field_language('node', $node1, 'field_panel_copy1') ][0]['value'];
                $hr1 = $node1->field_add_hr1[field_language('node', $node1, 'field_add_hr1') ][0]['value'];
                $rendered.= '<div class="panel-1-row panel-promo">';
                $nodeclass = $node1->field_nodeclass['und'][0]['value'];
                $rendered.= '<div class="panelBox '. $nodeclass . '">';
                $rendered.= $titlemain;
                $rendered.= '<div class="panel-item">';

                if ($img1) {
                  $rendered.= '
                    <div class="panel-image  col-lg-3 col-md-3 col-sm-3 col-xs-12">
                      <img ' .$img1alt.' src="' . $img1 . '">
                        ' . $miniimg1 . '
                    </div>';
                  $rendered.= '<div class="panel-copy col-lg-9 col-md-9 col-sm-9 col-xs-12">';
                }
                else {
                  $rendered.= '<div class="panel-copy col-xs-12 text-center">';
                }

                $rendered.= '<h3>' . $subtitile1 . '</h3>';
                $rendered.= $copy1;

                if ($linkurl1) {
                  $rendered.= '<p><a href="' . $linkurl1 . '" class="btn btn-primary">Learn More</a></p>';
                }

                if (!is_null($hr1)) {
                  $rendered.= '<hr/>';
                }

                $rendered.= '</div>';
                $rendered.= '</div>';
                $rendered.= '<div class="clearfix"></div>';
                $rendered.= '</div>';
                $rendered.= '</div>';
              }

              elseif ($tid == 2) {
                $subtitile1 = $node1->field_panel_sub_title1[field_language('node', $node1, 'field_panel_sub_title1') ][0]['value'];
                $subtitile2 = $node1->field_panel_sub_title2[field_language('node', $node1, 'field_panel_sub_title2') ][0]['value'];
                $copy1 = $node1->field_panel_copy1[field_language('node', $node1, 'field_panel_copy1') ][0]['value'];
                $copy2 = $node1->field_panel_copy2[field_language('node', $node1, 'field_panel_copy2') ][0]['value'];
                $hr1 = $node1->field_add_hr1[field_language('node', $node1, 'field_add_hr1') ][0]['value'];
                $hr2 = $node1->field_add_hr2[field_language('node', $node1, 'field_add_hr2') ][0]['value'];
                $rendered = '';
                $rendered.= '<div class="panel-2-col panel-promo">';
                $rendered.= '<div class="panelBox">';
                $rendered.= $titlemain;
                $rendered.= '<div class="col-lg-6 col-sm-6 col-xs-12 panel-item">';

                if ($img1) {
                  $rendered.= '<div class="panel-image">
                    <img src="' . $img1 . '">
                    ' . $miniimg1 . '
                  </div>';
                }

                $rendered.= '<div class="panel-copy text-center">';
                $rendered.= '<h3>' . $subtitile1 . '</h3>';
                $rendered.= $copy1;

                if ($linkurl1) { $rendered.= '<p><a href="' . $linkurl1 . '" class="">Learn More</a></p>'; }

                if (!is_null($hr1)) { $rendered.= '<hr/>'; }

                $rendered.= '</div>';
                $rendered.= '</div>';
                $rendered.= '<div class="col-lg-6 col-sm-6 col-xs-12 panel-item">';

                if ($img2) {
                  $rendered.= '  <div class="panel-image">
                    <img '.$img2alt.'src="' . $img2 . '">
                      ' . $miniimg2 . '
                  </div>';
                }

                $rendered.= '<div class="panel-copy text-center">';
                $rendered.= '<h3>' . $subtitile2 . '</h3>';
                $rendered.= $copy2;

                if ($linkurl2) { $rendered.= '<p><a href="' . $linkurl2 . '"class="">Learn More</a></p>'; }
                if (!is_null($hr2)) { $rendered.= '<hr/>'; }

                $rendered.= '</div>';
                $rendered.= '</div>';
                $rendered.= '<div class="clearfix"></div>';
                $rendered.= '</div>';
                $rendered.= '</div>';
              }

              elseif ($tid == 1) {
                $subtitile1 = $node1->field_panel_sub_title1[field_language('node', $node1, 'field_panel_sub_title1') ][0]['value'];
                $copy1 = $node1->field_panel_copy1[field_language('node', $node1, 'field_panel_copy1') ][0]['value'];
                $hr1 = $node1->field_add_hr1[field_language('node', $node1, 'field_add_hr1') ][0]['value'];
                $rendered.= '<div class="panel-1-col panel-promo">';
                $rendered.= '<div class="panelBox">';
                $rendered.= $titlemain;
                $rendered.= '<div class="col-xs-12 panel-item">';

                if ($img1) {
                  $rendered.= '<div class="panel-image">
                    <img ' .$img1alt.' src="' . $img1 . '">
                    ' . $miniimg1 . '
                  </div>';
                }

                $rendered.= '<div class="panel-copy text-center">';
                $rendered.= '<h3>' . $subtitile1 . '</h3>';
                $rendered.= $copy1;

                if ($linkurl1) {
                  $rendered.= '<p><a href="' . $linkurl1 . '">Learn More</a></p>';
                }

                if (!is_null($hr1)) { $rendered.= '<hr/>'; }

                $rendered.= '</div>';
                $rendered.= '</div>';
                $rendered.= '<div class="clearfix"></div>';
                $rendered.= '</div>';
                $rendered.= '</div>';
              }
            }
            // Content type ( related_content_panel ) Related Content Panel
            elseif ($node1->type == 'related_content_panel') {
              $rendered = '';
              // $noBg = $node1->field_no_background[field_language('node', $node1, 'field_no_background') ][0]['value'];

              // if ($noBg ===  '1') {
              //  $noBgSet = 'noBg';
              // }

              // $rendered.= '<div class="' . $noBgSet . '"><div class="panelBox"><div class="row"><div class="col-sm-12 related-content-title">' . $titlemain . '</div>';

              $rendered.= '<div class="panelBox"><div class="col-sm-12 related-content-title">' . $titlemain .'</div>';

              foreach($node1->field_assets_list[field_language('node', $node1, 'field_assets_list') ] as $value) {
                $node_cust_entityid = $value['target_id'];
                $node_cust_tnids = translation_node_get_translations($node_cust_entityid);

                // if there is a translated version of this item, switch to that ID
                if (isset($node_cust_tnids[$nnode->language])) {
                  $node_cust_entityid = $node_cust_tnids[$nnode->language]->nid;
                }

                $node_cust = node_load($node_cust_entityid);

                if (!empty($node_cust)) {
                  $style = 'image-style-original';
                  $imgsrc = '';

                  if (!is_null($node_cust->field_add_asset[field_language('node', $node_cust, 'field_add_asset') ][0]['uri'])) {
                    $imgsrc.= '<img class="primary"src="' . image_style_url($style, $node_cust->field_add_asset[field_language('node', $node_cust, 'field_add_asset') ][0]['uri']) . '"/>';
                  }

                  $asset_type = taxonomy_term_load($node_cust->field_asset_type[field_language('node', $node_cust, 'field_asset_type') ][0]['tid']);
                  $lang = field_language('taxonomy', $asset_type, 'field_style_class');
                  $lang = ($lang) ? $lang : LANGUAGE_NONE;
                  $ac_arr = array();
                  $ac_arr[] = $asset_type->field_style_class[$lang][0]['value'];
                  $ac_arr[] = 'ao-' . $node1->field_asset_output_type[field_language('node', $node1, 'field_asset_output_type') ][0]['value'];
                  $ac_arr[] = $node_cust->field_gated[field_language('node', $node_cust, 'field_gated') ][0]['value'] ? 'gated' : '';
                  $asset_class = implode(' ', $ac_arr);
                  $asset_url = '';

                  if ($node1->field_asset_output_type[field_language('node', $node1, 'field_asset_output_type') ][0]['value'] == 'normal') {

                    // field_asset_link is totally gone now
                    if (isset($node_cust->field_asset_link[field_language('node', $node_cust, 'field_asset_link') ][0]['target_id'])) {
                      $asset_rm_link = l("Learn More", "node/{$node_cust->nid}", array(
                        'attributes' => array(
                          'class' => array("btn btn-primary"))
                        )
                      );
                    }

                    elseif (isset($node_cust->field_group_external_link[field_language('node', $node_cust, 'field_group_external_link') ][0]['value'])) {
                      $link = field_collection_item_load($node_cust->field_group_external_link[field_language('node', $node_cust, 'field_group_external_link') ][0]['value']);
                      if ($asset_class == "rc-newscoverage ao-normal") {
                        $asset_rm_link = l('Learn More', $link->field_external_link[field_language('field_collection_item', $link, 'field_external_link') ? : LANGUAGE_NONE][0]['url'], array(
                          'attributes' => array(
                            'class' => array("btn btn-primary")
                          )
                        ));
                      }
                      else {
                        $asset_rm_link = l('Learn More', $link->field_external_link[field_language('field_collection_item', $link, 'field_external_link') ? : LANGUAGE_NONE][0]['url'], array('attributes' => array('class' => array("btn btn-primary field_group_external_link"))));
                      }
                    }

                    elseif (isset($node_cust->field_group_download[field_language('node', $node_cust, 'field_group_download') ][0]['value'])) {
                      $gated = $node_cust->field_gated[field_language('node', $node_cust, 'field_gated') ][0]['value'] ? 'gated' : '';
                      $link = field_collection_item_load($node_cust->field_group_download[field_language('node', $node_cust, 'field_group_download') ][0]['value']);

                      // big panel download link
                      $asset_rm_link = '<a data-asset="' . $asset_type->name . '" data-nid="' . $node_cust->nid . '" href="' . file_create_url($link->field_asset_download[field_language('field_collection_item', $link, 'field_asset_download') ][0]['uri']) . '" class="btn btn-primary ' . $gated . '" target="_blank">Download Now</a>';
                    }

                    elseif (isset($node_cust->field_group_video[field_language('node', $node_cust, 'field_group_video') ][0]['value'])) {
                      $video_entity = field_collection_item_load($node_cust->field_group_video[field_language('node', $node_cust, 'field_group_video') ][0]['value']);
                      $vid_id = $video_entity->field_video_player_uuid[field_language('field_collection_item', $video_entity, 'field_video_player_uuid') ? : LANGUAGE_NONE][0]['value'];

                      if ($vid_id) {
                        $asset_url = 'http://play.vidyard.com/' . $vid_id . '.html';
                        $asset_rm_link = '<a data-asset="' . $asset_type->name . '" data-nid="' . $node_cust->nid . '" href="' . $asset_url . '" class="btn btn-primary  field_asset_video_player_uuid ' . $asset_class . '">Watch Now</a>';
                      }
                    }

                    else { $asset_rm_link = ''; }

                    // CONDITIONAL - IS THE CONTENT PUBLISHED
                    if ($node_cust->status == '1') {
                      $rendered.= '
                      <div class="col-xs-12 col-sm-4 jt ' . $asset_class . '">
                        <div class="panel-item">
                          <div class="panel-image-wrapper">';
                            if ($imgsrc == NULL) {
                              $rendered.= '<div class="panel-image-icon"></div>';
                            } else {
                              $rendered.= '' . $imgsrc . '';
                            }
                            $rendered.= '</div>

                          <div class="panel-copy">
                            <h4>' . $asset_type->name . '</h4>
                            <h3>' . $node_cust->title . '</h3>
                            ' . $asset_rm_link . '
                          </div>

                          <div class="mask">';
                            // custom character limit on rollover
                            $bodystring = $node_cust->field_body[field_language('node', $node_cust, 'field_body') ][0]['value'];
                            $newbodystring = substr($bodystring, 0, 350);
                            $rendered.= '' . $newbodystring . '...
                          </div>
                          <div class="clearfix"></div>
                        </div>
                      </div>';
                    }
                  }

                  else {
                    $asset_rm = 'Learn More';

                    if ($asset_type->name) {
                      $asset_rm = 'Learn' . $asset_type->name;
                    }

                    if (isset($node_cust->field_asset_link[field_language('node', $node_cust, 'field_asset_link') ][0]['target_id'])) {
                      $node_link = drupal_get_path_alias('node/' . $node_cust->field_asset_link[field_language('node', $node_cust, 'field_asset_link') ][0]['target_id']);
                      $asset_url = url($node_link);
                      $asset_rm_link = '<a data-asset="' . $asset_type->name . '" href="' . $asset_url . '" class="read-more ' . $asset_class . '">' . $asset_rm . '</a>';
                    }

                    elseif (isset($node_cust->field_group_external_link[field_language('node', $node_cust, 'field_group_external_link') ][0]['value'])) {
                      $link = field_collection_item_load($node_cust->field_group_external_link[field_language('node', $node_cust, 'field_group_external_link') ][0]['value']);

                    // news coverage alt
                    if ($asset_class = "rc-newscoverage ao-alternative") {
                      $asset_rm_link = l('Learn More', $link->field_external_link[field_language('field_collection_item', $link, 'field_external_link') ? : LANGUAGE_NONE][0]['url'], array(
                        'attributes' => array('class' => array("read-more"))));
                    }

                    else {
                      $asset_rm_link = l('Learn More', $link->field_external_link[field_language('field_collection_item', $link, 'field_external_link') ? : LANGUAGE_NONE][0]['url'], array(
                        'attributes' => array('class' => array("read-more"))));
                    }
                  }

                  elseif (isset($node_cust->field_group_external_link[field_language('node', $node_cust, 'field_group_external_link') ][0]['value'])) {
                    $link = field_collection_item_load($node_cust->field_group_external_link[field_language('field_collection_item', $node_cust, 'field_group_external_link') ? : LANGUAGE_NONE][0]['value']);
                    $asset_rm_link = l('Learn More' . $asset_type->name, $link->field_external_link[field_language('node', $asset_type, 'field_external_link') ? : LANGUAGE_NONE][0]['url'], array(
                      'attributes' => array('class' => array("read-more"))));
                  }

                  // rc alt download link
                  elseif (isset($node_cust->field_group_download[field_language('node', $node_cust, 'field_group_download') ][0]['value'])) {
                    $link = field_collection_item_load($node_cust->field_group_download[field_language('node', $node_cust, 'field_group_download') ][0]['value']);
                    $gated = $node_cust->field_gated[field_language('node', $node_cust, 'field_gated') ][0]['value'] ? 'gated' : '';

                    // files don't get translated, so they use the EN version of the item.
                    $asset_rm_link = '<a data-asset="' . $asset_type->name . '" data-nid="' . $node_cust->nid . '" href="' . file_create_url($link->field_asset_download[field_language('field_collection_item', $link, 'field_asset_download') ][0]['uri']) . '" class="read-more ' . $gated . '" target="_blank">Download Now</a>';
                    /*                                  } elseif (isset($node_cust->field_asset_video_player_uuid[field_language('node', $node_cust, 'field_asset_video_player_uuid')][0]['value'])) {
                    $asset_url = 'http://play.vidyard.com/' . $node_cust->field_asset_video_player_uuid[field_language('node', $node_cust, 'field_asset_video_player_uuid')][0]['value'] . '.html';
                    $asset_rm_link = '<a href="' . $asset_url . '"class="read-more   ' . $asset_class . '">' . $asset_rm . '</a>';
                    */
                  }

                  elseif (isset($node_cust->field_group_video[field_language('node', $node_cust, 'field_group_video') ][0]['value'])) {
                    $video_entity = field_collection_item_load($node_cust->field_group_video[field_language('node', $node_cust, 'field_group_video') ][0]['value']);
                    $vid_id = $video_entity->field_video_player_uuid[field_language('field_collection_item', $video_entity, 'field_video_player_uuid') ? : LANGUAGE_NONE][0]['value'];
                    $asset_url = 'http://play.vidyard.com/' . $vid_id . '.html';
                    $asset_rm_link = '<a data-asset="' . $asset_type->name . '" data-nid="' . $node_cust->nid . '" href="' . $asset_url . '" class="read-more ' . $asset_class . '">Watch Now</a>';
                  }

                  else { $asset_rm_link = ''; }

                  // CONDITIONAL - IS THE CONTENT PUBLISHED
                  if ($node_cust->status == '1') {
                    $rendered.= ' <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 panel-item ' . $asset_class . '">
                      <div class="rc-icon ' . $asset_class . '"></div><div class="panel-copy">
                        <h3>' . $node_cust->title . '</h3>
                        <p>' . $asset_rm_link . '</p>
                      </div>
                    </div>';
                  }
                }
              }

              else {
                $rendered.= '<div class="col-xs-12 col-sm-4 ' . $asset_class . '"><div class="panel-item"><div class="panel-copy"></div></div></div>';
              }
            }

            // CLOSE TAG FOR RELATED CONTENT PANEL ALT
            $rendered.= '</div>';
          }

          else {
            $rendered = '<div class="custom">';
            $rendered.= '<div class="col-xs-12 panel-item">';
            $rendered.= $titlemain;
            $rendered.= '<div class="panel-copy">';
            $rendered.= $copy1;
            $rendered.= '</div>';
            $rendered.= '</div>';
            $rendered.= '<div class="clearfix">';
            $rendered.= '</div>';
            $rendered.= '</div>';
          }

          // LOGIC for related content panels class add for "is alternate"
          $collapsed = $node1->field_asset_output_type['und'][0]['value'];

          if ($collapsed !== 'normal') { $related = " is_alternate "; }

          $paneltype = $node1->type;

          if ($paneltype !== 'related_content_panel') { $related = " "; }

          $paneltype = $node1->type;
          $page[$region][$add_block_unique] = array(
            '#type' => 'markup',
            '#markup' => '<div class="adaptive_block ' . $name . ' ' . $panelcontainer . ' ' . $paneltype . $related .'" id="' . $add_block_unique . '">' . $rendered . '</div>'
          );
        }
      }
    }
  }
}
